# tasks file for pip
---
- name: PIP | Install dependencies
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  with_items: "{{ pip_dependencies }}"
  tags:
    - configuration
    - pip
    - pip-dependencies

- name: PIP | Install (latest) pip (setuptools and wheel)
  command: easy_install pip
  tags:
    - configuration
    - pip
    - pip-pip-install
